sg12/zulip

web/src/audio_call.ts, web/src/click_handlers.ts, web/src/compose_actions.ts, web/src/message_view.ts, web/src/topic_list.ts, web/src/ui_init.js, web/styles/compose.css, web/templates/audio_iframe.hbs, web/templates/compose.hbs, web/templates/compose_control_buttons.hbs, web/templates/confirm_dialog/confirm_create_topic.hbs, web/templates/popovers/compose_control_buttons/compose_control_buttons_in_popover.hbs
Убраны лишние кнопки из панели чата. Добавлены типы каналов при создании. Само создание помещено в модальное окно.
Видео конфа при создании открывается в iframe (в аудио каналах) (временно mit ji).
=> Dev upd chat panel

templates/zerver/app/index.html, web/src/ui_init.js, web/styles/right_sidebar.css, web/templates/navbar.hbs, web/templates/right_sidebar.hbs
=> Fix right sidebar

web/templates/message_controls.hbs, web/templates/popovers/left_sidebar/left_sidebar_topic_actions_popover.hbs, web/templates/popovers/message_actions_popover.hbs, web/templates/popovers/navbar/navbar_personal_menu_popover.hbs, web/templates/recipient_row.hbs, zerver/models/realms.py
=> Frontend n

zerver/models/users.py, zerver/views/users.py, zproject/urls.py
=> Добавил избранных пользователей для пользователя

web/src/compose_call_ui.ts
перенос логики создания iframe
=> dev[iframeJitsiAPI]: перенос логики создания iframe

web/src/stream_list.ts, web/src/stream_popover.ts, web/templates/change_avatar_stream_modal.hbs, web/templates/popovers/left_sidebar/left_sidebar_stream_actions_popover.hbs, web/templates/stream_sidebar_row.hbs
Добавлена возможность добавления/удаления аватарок каналов. Возможность доступна лишь создателю канала
=> dev change avatar stream

zerver/lib/upload/local.py, zerver/lib/upload/s3.py
=> Добавил вызов ошибки для теста.

web/src/invite.ts, web/src/onboarding_steps.ts, web/src/people.ts, web/styles/message_row.css, web/styles/settings.css, web/templates/buddy_list/view_all_subscribers.hbs, web/templates/buddy_list/view_all_users.hbs, web/templates/invite_user_modal.hbs, web/templates/message_hidden_dialog.hbs, web/templates/pm_list_item.hbs, web/templates/settings/settings_user_list_row.hbs, web/templates/settings_overlay.hbs
=> Change settings list

web/src/blueslip.ts, web/src/buddy_list.ts, web/templates/right_sidebar.hbs
=> Change userlist

web/src/resize.ts, web/styles/left_sidebar.css
фикс скроллинга левой боковой панели
=> dev[fixScrollLeftSideBar]: фикс скроллинга левой боковой панели

templates/zerver/accounts_home.html, web/templates/message_view_header.hbs
=> Change elements

web/src/stream_list.ts, web/src/stream_popover.ts, web/styles/left_sidebar.css, web/templates/stream_sidebar_row.hbs
=> dev[CON-22]: fix! Увеличить контейнер канала, согласно макету

web/src/color_data.ts, web/src/stream_data.ts
[CON-42](https://ru.yougile.com/team/2d060b5440f4/#CON-42)
=> dev[staticColorChannel]: статичный цвет для плашек канала

zerver/views/streams.py, zproject/prod_settings_template.py
=> Настроил почту и добавил проверки для каналов

zproject/prod_settings_template.py
=> *Update prod_settings_template.py

zerver/views/streams.py, zproject/prod_settings_template.py
=> Убрал пароль, он там не нужен

web/src/compose_call_ui.ts, web/src/stream_list.ts, web/src/topic_list.ts, web/templates/topic_list_item.hbs
[CON-57](https://ru.yougile.com/team/2d060b5440f4/#CON-57)
=> dev[CON-57]: [Ошибка] настройки комнаты: микрофон, камера и экран

web/src/resize.ts
[CON-75](https://ru.yougile.com/team/2d060b5440f4/#CON-75)
=> dev[listUsers]: fix! Список участников канала обрезается

web/src/click_handlers.ts
[CON-79](https://ru.yougile.com/team/2d060b5440f4/#CON-79)
=> dev[fixIconChannel]: fix! Сделать значки звуковых комнат едиными

web/src/compose.js, web/styles/compose.css, web/styles/zulip.css
[CON-84](https://ru.yougile.com/team/2d060b5440f4/#CON-84)
=> dev[scrollChat]: fix скроллинга чата
